### ISSUE TITLE
anvi-import-functions doesn't accept e-value of "-"

### ISSUE THREAD

**Issue by brymerr921** [edgraham/GhostKoalaParser#4]
When running KEGG-to-anvio on combined KEGG and InterProScan annotations, the resulting output file has some rows where the e-value is "-". The script anvi-import-functions doesn't like this, as it expects all entries in this column should be floats. I think the InterProScan parser built into anvi-import-functions converts all "-" in the e-value column to 0.

**Comment by edgraham** [comment]
This is fixed now, a couple of the interproscan databases don't output E-values so I've now set it to replace any null value with a 0.
