### ISSUE TITLE
Importing KEGG annotation to anvi'o

### ISSUE THREAD

**Issue by anaya1** [edgraham/GhostKoalaParser#5]
I have been trying to import functional KEGG annotations to anvi'o using GhostKoalaParse KEGG-to-anvio script. I am not sure what is going wrong but when running the command:
python KEGG-to-anvio --KeggDB samples/KO_Orthology_ko00001.txt -i ~/Documents/BMS_extraction/user_ko.txt -o ~/Documents/BMS_extraction/ko_anvio.txt
I am getting sth like this:
Traceback (most recent call last):
  File "KEGG-to-anvio", line 38, in <module>
    extracted= extracted.rename({'description':'function'},axis='columns')
  File "/Users/annaalessi/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2746, in rename
    **kwargs)
  File "/Users/annaalessi/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 694, in rename
    'argument "{0}"'.format(list(kwargs.keys())[0]))
TypeError: rename() got an unexpected keyword argument "axis"

The file I used to run it, is here:
[user_ko.txt](https://github.com/edgraham/GhostKoalaParser/files/1677392/user_ko.txt).
Many thanks for your help and any suggestions.

**Comment by edgraham** [comment]
This looks like it may be a python 3 error. Try running the script in
python 2 and let me know if it works. I can make the necessary adjustments
to make it python 3 compatable if thats the case.
