### ISSUE TITLE
Blank file when generating KEGG orthology table according to guide

### ISSUE THREAD

**Issue by kevinxchan** [edgraham/GhostKoalaParser#8]
Hi, I'm interested in generating the KEGG orthology table used in the guide (and in this repo) myself, but the command to get the `.keg` file appears to be broken. Specifically, the line
```
wget 'http://www.genome.jp/kegg-bin/download_htext?htext=ko00000.keg&format=htext&filedir=' -O ko00000.keg
```
gives me a blank `.keg` file. Is this link outdated? If so, could you please tell me which URL I should be using? Thanks.

**Comment by elzerac** [comment]
I found that I could just manually download the htext file here: https://www.genome.jp/kegg-bin/get_htext?ko00001

**Comment by kevinxchan** [comment]
Thank you! For future viewers who aren't as quick as me, there is an option on the top menu named `Download htext` where you can download it manually.
